spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.139.102:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-member

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000