spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.139.102:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  global-config:
    db-config:
      id-type: auto