spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: test_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
server:
  port: 88