spring:
  cloud:
    alicloud:
      access-key: LTAI5t8cnYAuFR2z9dN6RFX6
      secret-key: iWySIFNz0CGr3nsxEW4czwxHZ9p54g
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket : gulimall-xcx1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000